site_name: Lip Documentation
site_url: https://docs.lippkg.com
repo_name: LipPkg/Lip
repo_url: https://github.com/LipPkg/Lip/

nav:
  - Basics:
    - index.md
    - installation.md
    - quickstart.md
    - lipui_quickstart.md
    - creator_quickstart.md
    - faq.md
    - tooth_json_file_reference.md
    - Changelog: https://github.com/LipPkg/Lip/blob/main/CHANGELOG.md

  - Tutorials:
    - tutorials/create_a_lip_tooth.md

  - Commands:
    - commands/lip.md
    - commands/lip_autoremove.md
    - commands/lip_cache.md
    - commands/lip_cache_purge.md
    - commands/lip_install.md
    - commands/lip_list.md
    - commands/lip_show.md
    - commands/lip_tooth.md
    - commands/lip_tooth_init.md
    - commands/lip_tooth_pack.md
    - commands/lip_uninstall.md

  - Packages: https://www.lippkg.com

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  favicon: img/favicon.ico
  logo: img/logo.webp
  palette:
    primary: white

use_directory_urls: false

plugins:
  - i18n:
      languages:
        - locale: en
          default: true
          name: English
        - locale: zh
          name: 中文
          nav_translations:
            Basics: 基础
            Changelog: 更新日志
            Commands: 命令
            Languages: 语言
            Tutorials: 教程
