on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        GOOS: [darwin, linux, windows]
        GOARCH: [amd64, arm64]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
         cache: true
         cache-dependency-path: src/go.sum
         go-version-file: src/go.mod

      - name: Set up workspace
        run: go work init ./src

      - name: Build
        run: |
          export GOOS=${{ matrix.GOOS }}
          export GOARCH=${{ matrix.GOARCH }}
          go build -ldflags "-X 'github.com/liteldev/lip/context.VersionString=0.0.0' -s -w" -o ./build/ github.com/liteldev/lip

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.GOOS }}-${{ matrix.GOARCH }}
          path: build
