on:
  release:
    types: 
      - published

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        GOOS: [darwin, linux, windows]
        GOARCH: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
         cache: true

      - name: Build
        run: |
          export GOOS=${{ matrix.GOOS }}
          export GOARCH=${{ matrix.GOARCH }}
          go build -ldflags "-s -w" -o bin/ github.com/lippkg/lip/cmd/lip

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.GOOS }}-${{ matrix.GOARCH }}
          path: bin

  update-release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v2

      - uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.extract-release-notes.outputs.release_notes }}

  upload-to-release:
    needs: 
      - build
      - update-release-notes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        GOOS: [darwin, linux, windows]
        GOARCH: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.GOOS }}-${{ matrix.GOARCH }}
          path: artifact

      - name: Copy essential files
        run: |
          cp CHANGELOG.md LICENSE README.md artifact/

      - name: Pack artifact (Windows)
        if: matrix.GOOS == 'windows'
        run: |
          cd artifact
          zip -r ../lip-${{ matrix.GOOS }}-${{ matrix.GOARCH }}.zip *
          cd ..

      - name: Pack artifact (Others)
        if: matrix.GOOS != 'windows'
        run: |
          cd artifact
          tar -czvf ../lip-${{ matrix.GOOS }}-${{ matrix.GOARCH }}.tar.gz *
          cd ..

      - name: Upload artifact to release (Windows)
        if: matrix.GOOS == 'windows'
        uses: softprops/action-gh-release@v1
        with:
          append_body: true
          files: |
            lip-${{ matrix.GOOS }}-${{ matrix.GOARCH }}.zip

      - name: Upload artifact to release (Others)
        if: matrix.GOOS != 'windows'
        uses: softprops/action-gh-release@v1
        with:
          append_body: true
          files: |
            lip-${{ matrix.GOOS }}-${{ matrix.GOARCH }}.tar.gz
